name: Changelog

on:
  pull_request:
    types: [closed]

  push:
    tags:
      - 'v*'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
