name: Changelog

on:
  pull_request:
    types: [closed]

  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v0.7.0
